### ISSUE TITLE
Saving the covariance estimate to the graph file

### ISSUE THREAD

**Issue by kubelvla** [dan11003/CFEAR_Radarodometry_code_public#3]
Hi Dan, I was wondering where you save the covariance to your compact graph file, and I couldn't find it. Is this the place where you should be doing it? If I recall from our playing with the TBV, the covars were all unit, could this be this issue as well?

https://github.com/dan11003/CFEAR_Radarodometry_code_public/blob/e9c6ccb6c5a6aee992db24e645d4360b1eb5fb41/src/cfear_radarodometry/odometrykeyframefuser.cpp#L385

**Comment by dan11003** [comment]
Solved outside github.
